version: '3.7'
services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:9104
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8300:9104
    env_file:
      - ./.env.dev
