FROM springgos_base-web

# copy entrypoint-prod.sh
COPY ./entrypoint.prod.sh $APP_HOME

# copy project
COPY . $APP_HOME

# lint
RUN flake8 --ignore=E501,F401 $APP_HOME/api
RUN flake8 --ignore=E501,F401 $APP_HOME/config

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

# change to the app user
USER app

# run entrypoint.prod.sh
RUN ["chmod", "+x", "/home/app/web/entrypoint.prod.sh"]
ENTRYPOINT ["/home/app/web/entrypoint.prod.sh"]
